"""add_content_to_rss_articles

Revision ID: 097e52d4c126
Revises: ddde533ca0a3
Create Date: 2026-03-15 21:06:02.678359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097e52d4c126'
down_revision: Union[str, None] = 'ddde533ca0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_articles', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_articles', 'content')
    # ### end Alembic commands ###
