"""add_keyword_query_and_interval_schedule

Revision ID: 6dd80ba72039
Revises: 0128549c13e6
Create Date: 2026-03-10 18:46:28.696753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd80ba72039'
down_revision: Union[str, None] = '0128549c13e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('query', sa.String(length=1000), nullable=True))
    op.add_column('revue_keywords', sa.Column('interval_hours', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('revue_keywords', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revue_keywords', 'last_run_at')
    op.drop_column('revue_keywords', 'interval_hours')
    op.drop_column('keywords', 'query')
    # ### end Alembic commands ###
