"""initial_schema

Revision ID: 9d3cb9127183
Revises: 
Create Date: 2026-03-10 15:36:52.042531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3cb9127183'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('keywords',
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('transversal', 'exclusive', name='keywordtype'), nullable=False),
    sa.Column('frequency', sa.Enum('hourly', 'daily', 'weekly', name='searchfrequency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'client', 'support', name='accountrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('revues',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('revue_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_ar', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('tonality', sa.Enum('positive', 'neutral', 'negative', name='tonality'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'error', 'in_review', 'approved', 'modified', 'rejected', name='articlestatus'), nullable=False),
    sa.Column('scraping_error', sa.Enum('timeout', 'not_found', 'paywall', 'js_rendered', 'other', name='scrapingerror'), nullable=True),
    sa.Column('manually_entered', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['revue_id'], ['revues.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_table('revue_keywords',
    sa.Column('revue_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('max_results_per_run', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['revue_id'], ['revues.id'], ),
    sa.PrimaryKeyConstraint('revue_id', 'keyword_id')
    )
    op.create_table('user_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('revue_id', sa.UUID(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['revue_id'], ['revues.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'revue_id')
    )
    op.create_table('article_modification_logs',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.Column('fields_changed', sa.JSON(), nullable=False),
    sa.Column('original_values', sa.JSON(), nullable=False),
    sa.Column('new_values', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_modification_logs')
    op.drop_table('user_accounts')
    op.drop_table('revue_keywords')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('revues')
    op.drop_table('accounts')
    op.drop_table('keywords')
    op.drop_table('clients')
    # ### end Alembic commands ###
