"""add_media_sources_and_rss_articles

Revision ID: dd1fc052ade6
Revises: a1b2c3d4e5f7
Create Date: 2026-03-15 19:54:35.578886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1fc052ade6'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('rss_url', sa.String(length=2048), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('rss_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    op.create_table('rss_articles',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['media_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.drop_index('ix_collection_log_revue_id', table_name='collection_log')
    op.drop_index('ix_collection_log_triggered_at', table_name='collection_log')
    op.drop_table('collection_log')
    op.drop_table('scheduler_slot')
    op.drop_index('ix_article_reads_article_id', table_name='article_reads')
    op.drop_index('ix_article_reads_user_id', table_name='article_reads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_article_reads_user_id', 'article_reads', ['user_id'], unique=False)
    op.create_index('ix_article_reads_article_id', 'article_reads', ['article_id'], unique=False)
    op.create_table('scheduler_slot',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minute', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tbs', sa.VARCHAR(length=32), server_default=sa.text("'qdr:d'::character varying"), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=8), server_default=sa.text("'fr'::character varying"), autoincrement=False, nullable=False),
    sa.Column('num_results', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=32), server_default=sa.text("'google_news'::character varying"), autoincrement=False, nullable=False),
    sa.Column('gl', sa.VARCHAR(length=8), server_default=sa.text("'ma'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sort_by', sa.VARCHAR(length=16), server_default=sa.text("'relevance'::character varying"), autoincrement=False, nullable=False),
    sa.Column('safe_search', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['revue_id'], ['revues.id'], name='fk_scheduler_slot_revue_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scheduler_slot_pkey')
    )
    op.create_table('collection_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('revue_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('revue_name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=16), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tbs', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('collected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('errors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('duplicates', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['revue_id'], ['revues.id'], name='collection_log_revue_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='collection_log_pkey')
    )
    op.create_index('ix_collection_log_triggered_at', 'collection_log', ['triggered_at'], unique=False)
    op.create_index('ix_collection_log_revue_id', 'collection_log', ['revue_id'], unique=False)
    op.drop_table('rss_articles')
    op.drop_table('media_sources')
    # ### end Alembic commands ###
