"""add_image_author_to_rss_articles

Revision ID: ddde533ca0a3
Revises: dd1fc052ade6
Create Date: 2026-03-15 20:08:18.359695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddde533ca0a3'
down_revision: Union[str, None] = 'dd1fc052ade6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_articles', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('rss_articles', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_articles', 'author')
    op.drop_column('rss_articles', 'image_url')
    # ### end Alembic commands ###
